apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: migration
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30037
  type: NodePort