server:
  port: 1337

spring:
  application:
    name: migration-app
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    postgres:
      url: jdbc:postgresql://172.27.210.242:30037/migration
      username: migration
      password: migration
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 20
    mysql:
      url: jdbc:mysql://172.27.210.242:30036/migration?allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 20
  jpa:
    show-sql: true
---

management:
  tracing:
    enabled: true


logging:
  level:
    root: info
    org:
      springframework:
        web: DEBUG
        boot.context.properties: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

---
migration:
  datasource:
    url: jdbc:postgresql://172.27.210.242:30037/migration
    username: migration
    password: migration
    driver-class-name: org.postgresql.Driver
  batch-size: 5
  enabled: true
  mode: NON_INTERACTIVE
  rollback-strategy: FORCE
  jobs-package: com.example.demo.app.jobs
  executor: SEQUENTIAL
  versions:
    - "1.0.0"
    - "1.1.0"
    - "2.0.0"