apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysql
  namespace: migration
  labels:
    app: database
    environment: dev
    type: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      environment: dev
      type: database
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
        environment: dev
        type: database
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
          - containerPort: 3306 
        resources:
          requests:
            cpu: "2"
            memory: 2048Mi
          limits:
            cpu: "2"
            memory: 4096Mi
        env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: cm
                key: host

          - name: MYSQL_DBNAME
            valueFrom:
              configMapKeyRef:
                name: cm
                key: dbname

          - name: MYSQL_SCHEMA
            valueFrom:
              configMapKeyRef:
                name: cm
                key: schema
          
          # Secret values
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: root-password
          - name: MYSQL_PASSWORD

            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: mysql-root-password
          - name: MYSQL_USER
          
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: mysql-root-user
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql 
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc 