apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: migration
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30036
  type: NodePort